Repository 2025-Techeer-Summer-BootCamp-Team-E/frontend, pull requests merged in 2025-07, with the labels that each got.

#15 캐릭터 카드 퍼블리싱
  public/SampleCharacterCard.json
  src/assets/Icons/man.svg
  src/assets/Icons/woman.svg
  src/components/ActCharacterCard.tsx
  src/components/BackCharacterCard.tsx
  src/components/FrontCharacterCard.tsx
  src/pages/MyLibraryPage.tsx
Labels: design

#18 [Design] 로그인/회원가입 페이지 퍼블리싱
  src/App.tsx
  src/Layouts/AuthLayout.tsx
  src/assets/Icons/Logo.svg
  src/components/LoginView.tsx
  src/components/SignupView.tsx
  src/index.css
Labels: design

#19 컴포넌트 위치, 크기 수정
  src/components/BackCharacterCard.tsx
  src/components/FrontCharacterCard.tsx
  src/components/VideoInfo.tsx
  src/components/VideoInfoFetch.tsx
Labels: fix

#24 캐릭터 카드 선택 효과 구현
  src/assets/Icons/man.svg
  src/assets/Icons/woman.svg
  src/components/ActCharacterCard.tsx
  src/components/BackCharacterCard.tsx
  src/components/FrontCharacterCard.tsx
  src/pages/MyLibraryPage.tsx
Labels: style, design

#30 Design/#26
  index.html
  src/App.tsx
  src/assets/images/BookFloor.svg
  src/components/Header.tsx
  src/components/Toggle.tsx
  src/pages/MainPage.tsx
  tailwind.config.ts
Labels: design

#37 [Design] 내 영상 페이지 퍼블리싱
  public/SampleVideoInfo.json
  src/App.tsx
  src/Layouts/MainLayout.tsx
  src/components/Toggle.tsx
  src/components/VideoInfo.tsx
  src/components/VideoInfoFetch.tsx
  src/pages/MainPage.tsx
  src/pages/MyLibraryPage.tsx
  src/pages/MyVideosPage.tsx
Labels: design

#40 Design/#39
  src/App.css
  src/assets/Icons/Script.svg
  src/components/ActCharacterCard.tsx
  src/components/BackCharacterCard.tsx
  src/components/ConfirmModal.tsx
  src/components/FrontCharacterCard.tsx
  src/components/MoreCharacters.tsx
  src/pages/CharacterSelectPage.tsx
  src/pages/VideoCreatePage.tsx
Labels: refactor, design

#48 [Feat] 인물 생성 API 연동, 책 업로드 API 연동
  src/api/bookApi.ts
  src/api/characterApi.ts
  src/api/endpoints.ts
  src/components/ActCharacterCard.tsx
  src/components/BookUploadModal.tsx
  src/components/BooksSection.tsx
  src/components/CommonButton.tsx
  src/contexts/AuthContext.tsx
  src/pages/MyLibraryPage.tsx
  vite.config.ts
Labels: feat, fix, design

#52 [Feat] 대본 생성 페이지 API 연동
  src/api/characterApi.ts
  src/api/endpoints.ts
  src/components/ActCharacterCard.tsx
  src/components/BackCharacterCard.tsx
  src/components/ConfirmModal.tsx
  src/components/Script.tsx
  src/pages/CharacterSelectPage.tsx
  src/pages/MyLibraryPage.tsx
  src/pages/ScriptPage.tsx
  src/stores/appStore.ts
Labels: feat, design

#60 [DevOps] FE 레포 Vercel 배포
  .gitignore
  package.json
  src/assets/icons/BackIcon.svg
  src/assets/icons/Books_NonSelected.svg
  src/assets/icons/Books_Selected.svg
  src/assets/icons/Home.svg
  src/assets/icons/Login.svg
  src/assets/icons/Logo.svg
  src/assets/icons/MyVlog_NonSelected.svg
  src/assets/icons/MyVlog_Selected.svg
  src/assets/icons/Plus.svg
  src/assets/icons/Regenerating.svg
  src/assets/icons/Script.svg
  src/assets/icons/SearchIcon.svg
  src/assets/icons/Share.svg
  src/assets/icons/VideoIcon.svg
  src/assets/icons/down_flag.svg
  src/assets/icons/man.svg
  src/assets/icons/up_flag.svg
  src/assets/icons/woman.svg
  src/components/BackCharacterCard.tsx
  src/components/FrontCharacterCard.tsx
  src/components/Header.tsx
  src/components/Toggle.tsx
  src/layouts/AuthLayout.tsx
  src/layouts/MainLayout.tsx
  src/pages/CharacterSelectPage.tsx
  src/pages/MyLibraryPage.tsx
  src/pages/ScriptPage.tsx
  src/pages/TempPage.tsx
  src/pages/VideoCreatePage.tsx
  tsconfig.app.json
  vercel.json
Labels: devops, fix

#61 [Feat] 영상 생성 API 연동
  src/api/endpoints.ts
  src/api/videoApi.ts
  src/pages/ScriptPage.tsx
  src/pages/VideoCreatePage.tsx
Labels: feat, design

#70 [Feat] 영상 북마크 api 연동, 영상 재생 모달창 추가
  src/api/endpoints.ts
  src/api/videoApi.ts
  src/components/VideoInfo.tsx
  src/components/VideoInfoFetch.tsx
  src/components/VideoModal.tsx
  src/pages/MyLibraryPage.tsx
  src/pages/ScriptPage.tsx
Labels: feat, design

#78 [Fix] 책 캐러셀 UX 개선
  src/components/BooksSection.tsx
  src/pages/MyLibraryPage.tsx
Labels: fix

#79 [refactor] 영상 목록 조회 api 연동 수정
  src/api/endpoints.ts
  src/components/VideoInfo.tsx
  src/components/VideoInfoFetch.tsx
Labels: refactor

#82 [Design] 책 표지 로직 수정하여 자동으로 임시 표지 추가
  src/api/bookApi.ts
  src/assets/images/sample_cover1.png
  src/assets/images/sample_cover2.png
  src/assets/images/sample_cover3.png
  src/assets/images/sample_cover4.png
  src/pages/MyLibraryPage.tsx
Labels: design
